name: Deploy to Neocities

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Neocities CLI
      run: npm install -g neocities

    # Add npm global binaries to PATH for subsequent steps
    - name: Add npm global bin to PATH
      run: echo "$(npm bin -g)" >> $GITHUB_PATH

    - name: Deploy to Neocities
      run: neocities push ./ --key ${{ secrets.NEOCITIES_API_KEY }}
