name: Deploy to Neocities

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3. Install dependencies locally
      - name: Install dependencies
        run: npm install

      # 4. Deploy using npx (local package)
      - name: Deploy with npm script
      env:
        NEOCITIES_KEY: ${{ secrets.NEOCITIES_API_KEY }}
      run: npm run push